### ISSUE TITLE
Logger should be optional

### ISSUE THREAD

**Issue by vader-sama** [fastify/fastify-multipart#316]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi!
`fastify-multipart` logs unnecessary stuff, which I don't need!
I think there should be an option for the logger, something like a turn off switch.

### Example

```js
fastify.register(require("fastify-multipart"), { logger: false });
```

**Comment by jsumners** [comment]
I am closing this issue because:

1. The language and tone is disrespectful 
2. It is demanding of other's time
3. It does not include any information about which logs are not desired

Review the documentation on route logging -- https://www.fastify.io/docs/latest/Reference/Routes/#custom-log-level

If there is still a problem, open another issue that is more acceptable.
