### ISSUE TITLE
Sending empty of invalid multipart data crashes Fastify

### ISSUE THREAD

**Issue by schantaraud** [fastify/fastify-multipart#82]
Hi,

Here's a minimal example based on the addToBody example from the documentation:

```
const fastify = require('fastify')();

fastify.register(require('fastify-multipart'), {
  addToBody: true
})

fastify.post('/', function (req, reply) {
  console.log(req.body);
  reply.code(200).send();
})

fastify.ready()
  .then(() => {

    fastify.inject({
      method: 'post',
      url: '/',
      headers: {
        'content-type': 'multipart/form-data'
      }
    })
    .catch(error => {
      console.error('Error:', error);
    });
  });
```

The error is: `Multipart: Boundary not found`.

I'd be happy to help if you can point me in the right direction.

**Comment by Eomm** [comment]
Hi,
thank you for reporting!

In this case, the header must be changed accordingly to [HTTP docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST): `multipart/form-data;boundary="boundary"`

For sure crashing is not an option 😅: the problem is that we need to manage the error thrown here:

https://github.com/fastify/fastify-multipart/blob/efbca7ad2fdd7800d14f0ce00ed154335e80e081/index.js#L113

Would you like to give it a shot?

**Comment by schantaraud** [comment]
Yes, I can do this.

Test "should call finished when both files are pumped" fails on my system (Node v12.6.0), is it expected?
